### ISSUE TITLE
BusinessEvent og LifeEvent skal bare høstes som uri-referanser

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-public-service-harvester#15]
- [x] Refaktorer høsteren til samme format som fdk-event-harvester
- [x] Fjern høsting av events
- [x] Oppdater helm
- [x] Endre fulltxt til å hente events fra fdk-event-harvester

**Comment by shenluna** [comment]
Testet og verifisert
