### ISSUE TITLE
Mangler høsting og visning av spatial data for tjenester

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-public-service-harvester#19]
Relatert til:
https://github.com/Informasjonsforvaltning/behov/issues/445

Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/service/detail-default.html

Dette finnes på endepunktet:
https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-testdata/master/testdata/fdk-public-service-publisher.ttl

F.eks under "Søknad om skjenkebevillning":
dct:spatial <https://data.geonorge.no/administrativeEnheter/kommune/id/172833> ;

**Comment by shenluna** [comment]
Tjenester som ikke har lenke til kartverket vises med tom geografisk avgrensning
Eks: https://www.staging.fellesdatakatalog.digdir.no/public-services/d5d0c07c-c14f-3741-9aa3-126960958cf0
som bruker EU sine spartial adresser http://publications.europa.eu/resource/authority/country/NOR
![image](https://user-images.githubusercontent.com/73637969/111445213-7909af80-870b-11eb-9ac1-5e425381a641.png)

**Comment by shenluna** [comment]
Testet OK i staging

**Comment by shenluna** [comment]
Verifisert OK
