### ISSUE TITLE
Generer katalog for tjenester som mangler

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-public-service-harvester#56]
Etter samtale med Kurt Stian ble vi enige om å bruke lik strategi vedrørende kataloger som i begrepshøstingene

**Comment by terjesyl** [comment]
Hva er strategien? Og hva betyr det at en katalog genereres for tjenester som mangles?

**Comment by NilsOveTen** [comment]
> Hva er strategien? Og hva betyr det at en katalog genereres for tjenester som mangles?

i skos-ap-no og cpsv-ap-no er det ikke et krav at begrep/tjenester/hendelser ligger definert i en katalog. Siden det er et krav i dcat-ap-no har vi brukt det som et krav for hva som vises i fdk-portal. Det kunne vi ikke gjøre for disse andre, så alt som noen gang har blitt høstet vil alltid bli vist i fdk-portal. Det var ønskelig at begreper som hadde blitt fjernet fra høstekilden også skulle fjernes fra søket i fdk-portal.

Dette løste vi ved å simulere en katalog for hver høstekilde, som inneholder alle begrep som ikke allerede er lagt til i en skos:Collection. Den strategien med å simulere en katalog for hver høstekilde har vi valgt å videreføre for tjenester og hendelser, siden de vil ha samme problem med ressurser som blir liggende for evig i søket til fdk-portal.

for tjenestehøsteren vil det bety at om vi høster en kilde som inneholder en tjeneste uten katalog:
```
<https://test.no/service> a cpsv:PublicService ;
  dct:title "Høstet tjeneste"@nb .
```
Så vil høsteren legge til en generert katalog i rdf'en:
```
<https://test.no/service> a cpsv:PublicService ;
  dct:title "Høstet tjeneste"@nb .

<https://uri-til-høstekilde.no#GeneratedCatalog>
    a       dcat:Catalog ;
    dcatno:containsService <https://test.no/service> .
```
